spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: MYSQL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/task_manager?serverTimezone=UTC&useUnicode=true
    username: root
    password: dota21kmmr
  main:
    allow-bean-definition-overriding: true